config/routes.rb
Rails.application.routes.draw do

  get 'buy/new'

  get 'buy/create'

  get 'otp_test', to: 'otp_registration#new', as: 'otp_registration'
  post 'confirm_otp', to: 'otp_registration#confirm', as: 'confirm_otp'

  # get 'otp_registration/new,'

  # get 'otp_registration/create,'

  # get 'otp_registration/update'

  root 'main#homepage' # needs to be changed to main#show
  devise_for :clients, path: '', :controllers => { :confirmations => "confirmations" }, skip: [:sessions, :registrations, :passwords]
  as :client do
  #   #SignIn/SignOut[Sessions]
    get     'login', to: 'devise/sessions#new',      as: 'new_client_session'
    post    'login',  to: 'devise/sessions#create',   as: 'client_session'
    delete  'logout', to: 'devise/sessions#destroy',  as: 'destroy_client_session'

    #Registration
    get     'sign_up'   => 'devise_registrations#new',    as: 'new_client_registration'
    get     'sign_up/client' => 'devise_registrations#show', as: 'show_registration_form'
    get     'sign_up/show_licence' => 'devise_registrations#show_licence', as: 'show_licence'
    get     'sign_up/cancel' => 'devise_registrations#cancel', as: 'cancel_client_registration'
    get     'sign_up/edit'   => 'devise_registrations#edit', as: 'edit_client_registration'
    post    'sign_up'   => 'devise_registrations#create', as: 'client_registration'
    patch   'sign_up'   => 'devise_registrations#update'
    put     'sign_up'   => 'devise_registrations#update'
    delete  'sign_up'   => 'devise_registrations#destroy'

    #Password
    get   'reset'                => 'devise/passwords#new',      as: 'new_client_password'
    get   'reset/new_password'   => 'devise/passwords#edit',     as: 'edit_client_password'
    post  'reset'                => 'devise/passwords#create',   as: 'client_password'
    patch 'reset'                => 'devise/passwords#update'
    put   'reset'                => 'devise/passwords#update'
  end

  get '/wallet' => 'wallet#show', as: 'show_wallet'

  scope '/wallet' do
    get    '/buy/new'         => 'buy#new',              as: 'new_buy'
    post   '/buy/new'         => 'buy#create',           as: 'buy'
    get    '/sell/new'        => 'sell#new',             as: 'new_sell'
    post   '/sell'            => 'sell#create',          as: 'sell'
    get    '/withdraw/new'    => 'withdraw#new',         as: 'new_withdraw'
    post   '/withdraw'        => 'withdraw#create',      as: 'withdraw'
    get    '/transfer/show'   => 'transfer#show',        as: 'show_transfers'
    get    '/transfer/new'    => 'transfer#new',         as: 'new_transfer'
    post   '/transfer'        => 'transfer#create',      as: 'transfer'
    get    '/payment/show'    => 'payment#show',         as: 'show_payments'
    get    '/payment/new'     => 'payment#new',          as: 'new_payment'
    post   '/payment/new'     => 'payment#create',       as: 'payment_create_path'
    get    '/history'         => 'history#show',         as: 'history'
    delete '/payment/:id'     => 'payment#destroy',      as: 'delete'
  end

end

app/views/shared/_current_balance.html.erb
<span>Номер счета: <%= Account.encode(current_client.entity.in.to_i) %></span>
<span>Баланс: <%= "1000" %></span>

app/views/shared/_navbar.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="navbar-nav navbar-left">
        <% unless client_signed_in? %>
          <%= link_to 'OpenWalletKG', root_path, class: 'navbar-brand' %>
        <% else %>
          <%= link_to 'OpenWalletKG', show_wallet_path, class: 'navbar-brand' %>
             <p class="navbar-text">
                Привет!
             </p>
            <span class="glyphicon glyphicon-cog">
              <%= link_to "Настройки аккаунта", edit_client_registration_path %>
            </span>

        <% end %>
      </ul>
      <ul class="navbar-nav navbar-right">
      <% unless client_signed_in? %>
        <%= link_to 'Регистрация', new_client_registration_path, class: 'btn btn-default navbar-btn ow_btn' %>
        <%= link_to 'Вход', new_client_session_path, class: 'btn btn-default navbar-btn ow_btn' %>
      <% else %>
        <%= link_to 'Выход', destroy_client_session_path, method: :delete, class: 'btn btn-default navbar-btn' %>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="navbar-nav navbar-left">
        <% unless client_signed_in? %>
          <%= link_to 'OpenWalletKG', root_path, class: 'navbar-brand' %>
        <% else %>
          <%= link_to 'OpenWalletKG', show_wallet_path, class: 'navbar-brand' %>
             <p class="navbar-text">
                Привет, <%= current_client.entity.first_name %>!
             </p>
        <% end %>
      </ul>
      <ul class="navbar-nav navbar-right">
      <% unless client_signed_in? %>
        <%= link_to 'Регистрация', new_client_registration_path, class: 'btn btn-default navbar-btn' %>
        <%= link_to 'Вход', new_client_session_path, class: 'btn btn-default navbar-btn' %>
      <% else %>
        <%= link_to 'Выход', destroy_client_session_path, method: :delete, class: 'btn btn-default navbar-btn' %>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<div class="individual-sidebar">
  <%= link_to "Покупка электронных денег", new_buy_path, class: 'individual btn btn-primary navbar-btn' %><br>
  <%= link_to "Продажа электронных денег", show_wallet_path, class: 'individual btn btn-primary navbar-btn' %> <br>
  <%= link_to "Перевод электронных денег", show_transfers_path, class: 'individual btn btn-primary navbar-btn' %> <br>
  <%= link_to "Мои платежные системы", new_payment_path, class: 'individual btn btn-primary navbar-btn' %> <br>
  <%= link_to "Оплата", show_payments_path, class: 'individual btn btn-primary navbar-btn' %> <br>
  <%= link_to "История платежей", show_wallet_path, class: 'individual btn btn-primary navbar-btn' %> <br>
</div>