config/routes.rb
Rails.application.routes.draw do

  get 'buy/new'

  get 'buy/create'

  get 'otp_test', to: 'otp_registration#new', as: 'otp_registration'
  post 'confirm_otp', to: 'otp_registration#confirm', as: 'confirm_otp'

  # get 'otp_registration/new,'

  # get 'otp_registration/create,'

  # get 'otp_registration/update'

  root 'main#homepage' # needs to be changed to main#show
  devise_for :clients, path: '', :controllers => { :confirmations => "confirmations" }, skip: [:sessions, :registrations, :passwords]
  as :client do
  #   #SignIn/SignOut[Sessions]
    get     'login', to: 'devise/sessions#new',      as: 'new_client_session'
    post    'login',  to: 'devise/sessions#create',   as: 'client_session'
    delete  'logout', to: 'devise/sessions#destroy',  as: 'destroy_client_session'

    #Registration
    get     'sign_up'   => 'devise_registrations#new',    as: 'new_client_registration'
    get     'sign_up/client' => 'devise_registrations#show', as: 'show_registration_form'
    get     'sign_up/show_licence' => 'devise_registrations#show_licence', as: 'show_licence'
    get     'sign_up/cancel' => 'devise_registrations#cancel', as: 'cancel_client_registration'
    get     'sign_up/edit'   => 'devise_registrations#edit', as: 'edit_client_registration'
    post    'sign_up'   => 'devise_registrations#create', as: 'client_registration'
    patch   'sign_up'   => 'devise_registrations#update'
    put     'sign_up'   => 'devise_registrations#update'
    delete  'sign_up'   => 'devise_registrations#destroy'

    #Password
    get   'reset'                => 'devise/passwords#new',      as: 'new_client_password'
    get   'reset/new_password'   => 'devise/passwords#edit',     as: 'edit_client_password'
    post  'reset'                => 'devise/passwords#create',   as: 'client_password'
    patch 'reset'                => 'devise/passwords#update'
    put   'reset'                => 'devise/passwords#update'
  end

  get '/wallet' => 'wallet#show', as: 'show_wallet'

  scope '/wallet' do
    get    '/buy/new'         => 'buy#new',              as: 'new_buy'
    post   '/buy/new'         => 'buy#create',           as: 'buy'
    get    '/sell/new'        => 'sell#new',             as: 'new_sell'
    post   '/sell'            => 'sell#create',          as: 'sell'
    get    '/withdraw/new'    => 'withdraw#new',         as: 'new_withdraw'
    post   '/withdraw'        => 'withdraw#create',      as: 'withdraw'
    get    '/transfer/show'   => 'transfer#show',        as: 'show_transfers'
    get    '/transfer/new'    => 'transfer#new',         as: 'new_transfer'
    post   '/transfer'        => 'transfer#create',      as: 'transfer'
    get    '/payment/show'    => 'payment#show',         as: 'show_payments'
    get    '/payment/new'     => 'payment#new',          as: 'new_payment'
    post   '/payment/new'     => 'payment#create',       as: 'payment_create_path'
    get    '/history'         => 'history#show',         as: 'history'
    delete '/payment/:id'     => 'payment#destroy',      as: 'delete'
  end

end

app/controllers/payment_controller.rb
class PaymentController < WalletController
  before_action :authenticate_client!

  def new
    @account = Account.new
    @bank_accounts = Account.where(client_id: current_client.id, type: 'PaymentSystem')
  end

  def create
    if Account.add_bank_account(current_client, account_params, params[:bank_id])
      flash[:danger] = "Номер банковского счета успешно добавлен!"
      redirect_to '/wallet/payment/new'
    else
      flash[:danger] = "Номер банковского счета не найден!"
      redirect_to :back
    end
  end

  def destroy
    @account = Account.find(params[:id])
    @account.destroy
    flash[:notice] = "Ваш банковский счет удален"
    redirect_to '/wallet/payment/new'
  end


  def account_params
    params.require(:account).permit(:number, :type, :title, :client_id)
  end
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/views/payment/new.html.erb
<div class="col-md-8 show-account">
  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
  <% end %>
</div>
<div class="row">

  <div class="col-sm-6 col-md-6 ">
    <h1> Мои счета: </h1>
    <% @bank_accounts.each do |account| %>
        <div class="caption">
          <p><h4>Номер Счета: <%= account.number %></h4>
          <p><h4>Название Счета: <%= account.title %></h4>
          <%= link_to "Удалить счет", delete_path(account), method: :delete, class: 'btn btn-danger'  %>
        </div>
    <% end %>
  </div>

  <div class="col-sm-6 col-md-6 ">
    <h1>Добавление банковского счета: </h1>
    <div class="caption">
      <%= form_for :account, url: {action: "new"} do |f| %>
          <div class="field">
            <%= f.hidden_field :type, value: 'PaymentSystem' %>
          </div>

          <div class="field">
            <% bank_array = Bank.all.map { |bank| [bank.name, bank.id] } %>
            <%= select_tag :bank_id, options_for_select(bank_array) %>
          </div>

          <div class="field">
            <%= f.label :number, "Введите номер счета" %> <br>
            <%= f.text_field :number %>
          </div>

          <div class="field">
            <%= f.label :title, "Название счета" %> <br>
            <%= f.text_field :title %>
          </div>

          <div>
            <%= f.submit "Cохранить", class: 'btn btn-success'  %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/payment/show.html.erb
<div class="row">
  <div class="col-md-9 col-md-3-offset">
    <%= render 'shared/payment/main' %>
    <%= render 'shared/payment/services' %>
  </div>
</div>
<div class="row">

  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <!-- form start -->
            <%= render 'shared/payment/form' %>
          <!-- form end -->
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    
  </div>
</div>