config/routes.rb
Rails.application.routes.draw do

  get 'buy/new'

  get 'buy/create'

  get 'otp_test', to: 'otp_registration#new', as: 'otp_registration'
  post 'confirm_otp', to: 'otp_registration#confirm', as: 'confirm_otp'

  # get 'otp_registration/new,'

  # get 'otp_registration/create,'

  # get 'otp_registration/update'

  root 'main#homepage' # needs to be changed to main#show
  devise_for :clients, path: '', :controllers => { :confirmations => "confirmations" }, skip: [:sessions, :registrations, :passwords]
  as :client do
  #   #SignIn/SignOut[Sessions]
    get     'login', to: 'devise/sessions#new',      as: 'new_client_session'
    post    'login',  to: 'devise/sessions#create',   as: 'client_session'
    delete  'logout', to: 'devise/sessions#destroy',  as: 'destroy_client_session'

    #Registration
    get     'sign_up'   => 'devise_registrations#new',    as: 'new_client_registration'
    get     'sign_up/client' => 'devise_registrations#show', as: 'show_registration_form'
    get     'sign_up/show_licence' => 'devise_registrations#show_licence', as: 'show_licence'
    get     'sign_up/cancel' => 'devise_registrations#cancel', as: 'cancel_client_registration'
    get     'sign_up/edit'   => 'devise_registrations#edit', as: 'edit_client_registration'
    post    'sign_up'   => 'devise_registrations#create', as: 'client_registration'
    patch   'sign_up'   => 'devise_registrations#update'
    put     'sign_up'   => 'devise_registrations#update'
    delete  'sign_up'   => 'devise_registrations#destroy'

    #Password
    get   'reset'                => 'devise/passwords#new',      as: 'new_client_password'
    get   'reset/new_password'   => 'devise/passwords#edit',     as: 'edit_client_password'
    post  'reset'                => 'devise/passwords#create',   as: 'client_password'
    patch 'reset'                => 'devise/passwords#update'
    put   'reset'                => 'devise/passwords#update'
  end

  get '/wallet' => 'wallet#show', as: 'show_wallet'

  scope '/wallet' do
    get    '/buy/new'         => 'buy#new',              as: 'new_buy'
    post   '/buy/new'         => 'buy#create',           as: 'buy'
    get    '/sell/new'        => 'sell#new',             as: 'new_sell'
    post   '/sell'            => 'sell#create',          as: 'sell'
    get    '/withdraw/new'    => 'withdraw#new',         as: 'new_withdraw'
    post   '/withdraw'        => 'withdraw#create',      as: 'withdraw'
    get    '/transfer/show'   => 'transfer#show',        as: 'show_transfers'
    get    '/transfer/new'    => 'transfer#new',         as: 'new_transfer'
    post   '/transfer'        => 'transfer#create',      as: 'transfer'
    get    '/payment/show'    => 'payment#show',         as: 'show_payments'
    get    '/payment/new'     => 'payment#new',          as: 'new_payment'
    post   '/payment/new'     => 'payment#create',       as: 'payment_create_path'
    get    '/history'         => 'history#show',         as: 'history'
    delete '/payment/:id'     => 'payment#destroy',      as: 'delete'
  end

end

app/models/otp_registration.rb
class OtpRegistration < ApplicationRecord
  belongs_to :draft_phone_registration
end

app/controllers/otp_registration_controller.rb
class OtpRegistrationController < ApplicationController

  def new
    @mobile = params[:mobile]
    @phone = params[:mobile]
    @mobile.insert(0, "+")
    # @otp = DraftPhoneRegistration.last
    @otp = OtpSender.new(@mobile)
    @try_counts = @otp.get_try_counts
    @otp.send_otp_code
    if @try_counts < 5
      @message = "Вам был отправлен код подтверждения!"
      respond_to do |format|
        format.js {}
      end
    else  
      flash[:error] = "Вы превысили количество попыток ввода кода."
      render js: "window.location = '#{root_path}'"
    end  
  end

  def confirm
    @mobile = params[:mobile]
    check = OtpVerifier.new(@mobile)
    @try_counts = check.get_try_counts
    entered_pin = params[:pin]
    @pin_verified = check.verify_otp_code(entered_pin)
    if @pin_verified
      @message = "Ваш номер телефона был подтвержден"
      # render js: "window.location = '#{root_path}'"
      session[:pin_verified] = true
      respond_to do |format|
        format.js {} 
      end
    elsif @try_counts < 5
      @message = <<-HEREDOC
        Неверный код!
        Пожалуйста запросите код еще раз.
      HEREDOC
      respond_to do |format|
        format.js {}
      end 
    else
      flash[:error] = "Вы превысили количество попыток ввода кода."
      render js: "window.location = '#{root_path}'"
    end  
  end

  private 

  def mobile_params
    params.require(:mobile).permit(:mobile, :pin)
  end

end

app/helpers/otp_registration_helper.rb
module OtpRegistrationHelper
end

app/views/otp_registration/_otp_confirm.html.erb
<h4> <%= @message %> </h4>
<%= form_tag(confirm_otp_path, method: 'post', remote: true) do  %>
  <p id = "time"></p>
  <p id = "rezult"></p>
  <p> Осталось попыток <%= 5-@try_counts %></p>
  
  <%= text_field_tag :pin, nil, placeholder: "Введите код", class: "form-control" %>
  <%= hidden_field_tag :mobile, @mobile  %>
  <input type="button" id="bot" name="otp" onclick="get_otp_again()" value="Получить ОТП повторно" class="registration_form_btn" >
  <%= submit_tag "Подтвердить", name: 'confirm', class: 'registration_form_btn' %>
<%end%>

<script type="text/javascript">
  function get_otp_again() {
    var mob = document.getElementById("client_client_mobile").value;
    $.ajax({
      type: 'get',
      url: "/otp_test",
      data: {mobile: mob},
      response: 'text',
      success: function(){
            testTimer (10);
           },
      error: function () {
        alert('Ошибка отправки');
      }
    });
  }

</script>

app/views/otp_registration/confirm.js.erb
console.log('confirm');
<% if @pin_verified %>

  pin_verified = true;
  $('#new_client').submit();
  $('#otp_form').hide();
<% else %>
  $('#otp_confirmation').html("<%= escape_javascript(render partial: 'otp_confirm') %>");
<% end %> 

app/views/otp_registration/create.html.erb
<h1>OtpRegistration#create,</h1>
<p>Find me in app/views/otp_registration/create,.html.erb</p>

app/views/otp_registration/new.js.erb
$('#otp_confirmation').html("<%= escape_javascript(render partial: 'otp_confirm') %>");

app/views/otp_registration/test_otp_confirm.html.erb
<%= form_tag confirm_otp_path, remote: true, method: :post do |f| %>
  <%= otp.get_try_counts %>

  <%= submit_tag "Send" %>
  <!-- <h1>OTP cde has been sent to your phone</h1>
  <h2 class="fs-title">Подтверждение</h2>
  <h3 class="fs-subtitle">Проверка ОТП</h3>
  <p id = "time1"></p>
  <p id = "rezult1"></p>
  <p>Осталось попыток "5"</p>
  <input type="text" name="" placeholder="Введите код" />
  <input type="button" id="bot1" name="otp" onclick="testTimer1 (10)" value="Получить ОТП повторно"/>
  <input type="button" name="otp" value="Подтвердить"/> -->
<% end %>

app/views/otp_registration/update.html.erb
<h1>OtpRegistration#update</h1>
<p>Find me in app/views/otp_registration/update.html.erb</p>